issue-490, implementation for credentials lifecycle for ZooKeeper
instaclustr/operator pull request #493
Opened 2023-07-24 14:00 UTC by OleksiienkoMykyta

Closes #490

2023-07-25 14:48 UTC, RostislavPorohnya requested changes

2023-07-25 14:48 UTC, RostislavPorohnya commented on apis/clusters/v1beta1/zookeeper_types.go
> +	v1 "k8s.io/api/core/v1"
dont use alias

2023-07-25 15:03 UTC, OleksiienkoMykyta commented on apis/clusters/v1beta1/zookeeper_types.go
> +	v1 "k8s.io/api/core/v1"
fixed

2023-07-25 15:03 UTC, OleksiienkoMykyta commented on pkg/instaclustr/client.go
> +	var creds credentials
fixed

2023-07-25 15:17 UTC, RostislavPorohnya approved these changes

2023-07-26 11:19 UTC, taaraora approved these changes

2023-07-26 13:15 UTC, ribaraka approved these changes

2023-07-26 13:15 UTC, merged