Update opensearch doc
instaclustr/operator pull request #508
Opened 2023-07-31 13:09 UTC by ribaraka

Updated OpenSearch documentation to API v2

2023-07-31 13:53 UTC, RostislavPorohnya commented on doc/clusters/opensearch.md
> +| dashboards               | Array of objects ([Dashboards](#Dashboards))                           | List of dashboards settings
dashboard node settings

2023-07-31 14:03 UTC, ribaraka commented on doc/clusters/opensearch.md
> +| nodesNumber         | Int32  <br /> **required**  _mutable_       | Number of nodes   |
fixed

2023-07-31 14:25 UTC, ribaraka commented on doc/clusters/opensearch.md
> +| dashboards               | Array of objects ([Dashboards](#Dashboards))                           | List of dashboards settings
fixed

2023-07-31 14:27 UTC, ribaraka commented on doc/clusters/opensearch.md
> +| nodesNumber         | Int32  <br /> **required**  _mutable_       | Number of nodes   |
added + replaced `<br />` by `<br>`

2023-08-01 12:17 UTC, testisnullus requested changes

2023-08-01 12:17 UTC, testisnullus commented on doc/clusters/opensearch.md
> +| version                  | String <br> **required**                                               | OpenSearch instance version.
String -> string, Int -> int...

2023-08-01 12:39 UTC, ribaraka commented on doc/clusters/opensearch.md
> +| version                  | String <br> **required**                                               | OpenSearch instance version.
fixed

2023-08-01 16:57 UTC, testisnullus approved these changes

2023-08-03 09:47 UTC, merged