Added cassandra user creation/deletion integration test
instaclustr/operator pull request #518
Opened 2023-08-07 12:34 UTC by ribaraka

- added a `User` model to an Instaclustr server stub; added functioned endpoints of user management (create, delete)
- combined several API group controllers to display a basic test of creating/deleting Cassandra User

2023-08-08 15:28 UTC, testisnullus requested changes

2023-08-08 16:54 UTC, ribaraka commented on Makefile
> +
added

2023-08-09 09:30 UTC, testisnullus requested changes

2023-08-09 09:30 UTC, testisnullus commented on controllers/clusters/cassandra_controller.go
> +	l.Info("User has been set on creation", "username", u.Name)
User has been set on creation/deletion -> User has been added to the queue for creation/deletion

2023-08-09 10:22 UTC, testisnullus approved these changes

2023-08-09 10:25 UTC, merged