Kafka cluster CRD spec was updated with Kraft field
instaclustr/operator pull request #529
Opened 2023-08-22 13:30 UTC by tengu-alt

2023-08-22 14:08 UTC, testisnullus requested changes

2023-08-22 14:08 UTC, testisnullus commented on pkg/models/errors.go
> +	ErrImmutableKraft                        = errors.New("Kraft is immutable")
Kraft -> kraft

2023-08-22 14:08 UTC, testisnullus commented on pkg/models/errors.go
> +	ErrMoreThanThreeControllerNodeCount      = errors.New("Kraft does not support more than three controller nodes")
Kraft -> kraft

2023-08-22 15:57 UTC, worryg0d commented on pkg/models/kafka_apiv2.go
> +	Kraft                             []*Kraft                  `json:"kraft"`
```suggestion
	Kraft                             []*Kraft                  `json:"kraft,omitempty"`
```

2023-08-23 12:21 UTC, tengu-alt commented on pkg/models/errors.go
> +	ErrImmutableKraft                        = errors.New("Kraft is immutable")
done

2023-08-23 12:22 UTC, tengu-alt commented on pkg/models/errors.go
> +	ErrMoreThanThreeControllerNodeCount      = errors.New("Kraft does not support more than three controller nodes")
refactored

2023-08-23 13:50 UTC, ribaraka approved these changes

2023-08-23 13:50 UTC, ribaraka commented on pkg/models/errors.go
> +	ErrMoreThanOneKraft                      = errors.New("cluster spec spec does not support more than one kraft")
spec spec

2023-08-23 14:55 UTC, tengu-alt commented on pkg/models/errors.go
> +	ErrMoreThanOneKraft                      = errors.New("cluster spec spec does not support more than one kraft")
refactored

2023-08-23 16:24 UTC, testisnullus approved these changes

2023-08-23 17:26 UTC, worryg0d approved these changes

2023-08-24 16:25 UTC, merged