Issue-635 ApiExtensions package
instaclustr/operator pull request #653
Opened 2023-12-21 09:08 UTC by worryg0d

This PR adds `apiextensions` package which provides shared objects as:
* `ObjectReference`
* `ObjectFieldReference`
* `LocalObjectReference`
* `LocalObjectFieldReference`

2023-12-21 09:23 UTC, ribaraka approved these changes

2023-12-22 10:51 UTC, testisnullus requested changes

2023-12-22 10:51 UTC, testisnullus commented on pkg/apiextensions/doc.go
> +package apiextensions
Remove this file please

2023-12-22 10:51 UTC, testisnullus commented on pkg/apiextensions/references.go
> +type ObjectFieldReference struct {
What does the ObjectField mean?

2023-12-22 11:22 UTC, worryg0d commented on pkg/apiextensions/doc.go
> +package apiextensions
Removed

2024-01-02 14:37 UTC, worryg0d commented on pkg/apiextensions/references.go
> +}
We cannot use it because its fields doesn't have json tags

2024-01-02 14:38 UTC, DoodgeMatvey commented on pkg/apiextensions/references.go
> +}
agree

2024-01-02 14:38 UTC, DoodgeMatvey approved these changes

2024-01-02 15:40 UTC, testisnullus approved these changes

2024-01-02 15:40 UTC, merged