on premises automation has been removed by default
instaclustr/operator pull request #678
Opened 2024-01-18 15:41 UTC by testisnullus

2024-01-22 11:27 UTC, ribaraka requested changes

2024-01-22 11:27 UTC, ribaraka commented on apis/clusters/v1beta1/cadence_webhook.go
> +	exists, err := KubeVirtAddonExists(ctx, cv.Client)
ContainsKubeVirtAddon

2024-01-22 11:27 UTC, ribaraka commented on apis/clusters/v1beta1/kafka_webhook.go
> +			return fmt.Errorf("cannot create KubeVirt based resources automatially without KubeVirt operator " +
make a var of it

2024-01-22 11:27 UTC, ribaraka commented on apis/clusters/v1beta1/validation.go
> +		if checkKubeVirtLabels(deployment.Labels) || checkKubeVirtLabels(deployment.Annotations) {
containsKubeVirtLabels

2024-01-22 11:27 UTC, ribaraka commented on controllers/clusters/kafka_controller.go
> +		if client.IgnoreNotFound(err) != nil {
revert it pls

2024-01-22 11:27 UTC, ribaraka commented on controllers/clusters/cadence_controller.go
> +		if c.Spec.OnPremisesSpec != nil && c.Spec.OnPremisesSpec.EnableAutomation {
add the same condition for creation

2024-01-22 12:01 UTC, testisnullus commented on apis/clusters/v1beta1/cadence_webhook.go
> +	exists, err := KubeVirtAddonExists(ctx, cv.Client)
Agreed, fixed

2024-01-22 12:01 UTC, testisnullus commented on apis/clusters/v1beta1/kafka_webhook.go
> +			return fmt.Errorf("cannot create KubeVirt based resources automatially without KubeVirt operator " +
fixed

2024-01-22 12:01 UTC, testisnullus commented on apis/clusters/v1beta1/validation.go
> +		if checkKubeVirtLabels(deployment.Labels) || checkKubeVirtLabels(deployment.Annotations) {
ok, fixed

2024-01-22 12:02 UTC, testisnullus commented on controllers/clusters/kafka_controller.go
> +		if client.IgnoreNotFound(err) != nil {
Ok, fixed

2024-01-22 12:02 UTC, testisnullus commented on controllers/clusters/cadence_controller.go
> +		if c.Spec.OnPremisesSpec != nil && c.Spec.OnPremisesSpec.EnableAutomation {
Added

2024-01-24 09:24 UTC, ribaraka approved these changes

2024-01-24 19:09 UTC, taaraora approved these changes

2024-01-24 19:10 UTC, merged