Opensearch status update
instaclustr/operator pull request #682
Opened 2024-01-22 10:27 UTC by worryg0d

2024-01-25 14:02 UTC, ribaraka requested changes

2024-01-26 11:40 UTC, worryg0d commented on controllers/clusters/opensearch_controller.go
> +			if !dcEquals {
Fixed

2024-01-26 11:40 UTC, worryg0d commented on controllers/clusters/opensearch_controller.go
> +	l := log.Log.WithValues("openSearchStatusJob", o.GetJobID(scheduler.StatusChecker))
Fixed

2024-01-26 11:40 UTC, worryg0d commented on controllers/clusters/cadence_controller.go
> +			NumberOfRacks:       osReplicationFactor,
Fixed

2024-01-26 11:40 UTC, worryg0d commented on apis/clusters/v1beta1/opensearch_webhook.go
> +			return fmt.Errorf("number of data nodes must be a multiple of replication factor: %v", dc.NumberOfRacks)
Fixed

2024-01-26 11:40 UTC, worryg0d commented on apis/clusters/v1beta1/opensearch_types.go
> +			GenericDataCentreFields: models.GenericDataCentreFields{
I'll do it in other PR because there are some conflicts with current implementation of generic cluster spec

2024-01-26 11:40 UTC, worryg0d commented on apis/clusters/v1beta1/opensearch_types.go
> +		},
Done

2024-01-26 11:41 UTC, worryg0d commented on apis/clusters/v1beta1/generic_status_fields.go
> +func (n *Node) FromInstAPI(model *models.Node) {
:unamused: fixed

2024-01-26 11:41 UTC, worryg0d commented on apis/clusters/v1beta1/generic_status_fields.go
> +	return n.ID == o.ID &&
I think the `Equles` should compare the whole object

2024-01-26 11:41 UTC, worryg0d commented on apis/clusters/v1beta1/generic_status_fields.go
> +package v1beta1
Done

2024-01-26 13:27 UTC, ribaraka approved these changes

2024-01-26 14:04 UTC, testisnullus requested changes

2024-01-29 08:27 UTC, worryg0d commented on apis/clusters/v1beta1/opensearch_types.go
> +func (s *OpenSearchSpec) clusterManagerNodesFromInstAPI(clusterManagerNodeModels []*models.ClusterManagerNodes) {
Done

2024-01-29 14:13 UTC, testisnullus approved these changes

2024-01-29 14:13 UTC, testisnullus commented on pkg/instaclustr/mock/server/go/api_open_search_provisioning_v2.go
> +	//d.DisallowUnknownFields()
Let's remove it maybe

2024-01-29 14:54 UTC, merged