Generics refactor
instaclustr/operator pull request #692
Opened 2024-01-30 12:42 UTC by worryg0d

The PR provides refactor of generic fields of the cluster resources

2024-01-31 11:49 UTC, ribaraka requested changes

2024-02-01 10:02 UTC, worryg0d commented on apis/clusters/v1beta1/generic_spec.go
> +	PrivateNetworkCluster bool `json:"privateNetworkCluster,omitempty"`
Removed

2024-02-01 10:02 UTC, worryg0d commented on apis/clusters/v1beta1/generic_spec.go
> +	s.Description = model.Description
Fixed

2024-02-01 10:02 UTC, worryg0d commented on apis/clusters/v1beta1/generic_spec.go
> +	}
Removed

2024-02-01 10:02 UTC, worryg0d commented on apis/clusters/v1beta1/generic_spec.go
> +	settingsToAPI := &models.ClusterSettings{}
Done

2024-02-01 11:11 UTC, ribaraka requested changes

2024-02-01 11:11 UTC, ribaraka commented on controllers/clusters/opensearch_controller.go
> +	err := r.startClusterStatusJob(o)
startClusterStatusJob -> startClusterSyncJob

2024-02-01 11:11 UTC, ribaraka commented on pkg/instaclustr/client.go
> +func (c *Client) CreateOpenSearchCluster(url string, spec, dst any) error {
delete it

2024-02-01 11:54 UTC, worryg0d commented on pkg/instaclustr/client.go
> +func (c *Client) CreateOpenSearchCluster(url string, spec, dst any) error {
Done

2024-02-01 11:54 UTC, worryg0d commented on controllers/clusters/opensearch_controller.go
> +	err := r.startClusterStatusJob(o)
Done

2024-02-01 11:54 UTC, worryg0d commented on apis/clusters/v1beta1/opensearch_types.go
> +				Name:                  dc.Name,
Done

2024-02-01 11:54 UTC, worryg0d commented on Makefile
> + test: #manifests generate fmt vet docker-build-server-stub run-server-stub envtest test-clusters test-clusterresources test-kafkamanagement test-users stop-server-stub
reverted

2024-02-01 12:06 UTC, ribaraka approved these changes

2024-02-01 12:32 UTC, merged