Kafka codebase refactor
instaclustr/operator pull request #701
Opened 2024-02-06 14:28 UTC by worryg0d

The PR provides refactor of the Kafka codebase. Also there are some code cleanups, logs verboses, etc.

2024-02-07 13:24 UTC, worryg0d commented on config/samples/clusters_v1beta1_cassandra.yaml
> +      debezium:
Done

2024-02-07 13:24 UTC, worryg0d commented on controllers/clusters/kafka_controller.go
> +	l := log.Log.WithValues("component", "kafkaStatusClusterJob", "clusterID", k.Status.ID)
Done

2024-02-07 13:24 UTC, worryg0d commented on controllers/clusters/kafka_controller.go
> +		if equals && k.Annotations[models.ExternalChangesAnnotation] == models.True {
Done

2024-02-07 14:36 UTC, ribaraka requested changes

2024-02-07 14:36 UTC, ribaraka commented on controllers/clusters/helpers.go
> +func autoHandleExternalChanges(c client.Client, r record.EventRecorder, obj Object) error {
reconcileExternalChanges

2024-02-07 19:09 UTC, testisnullus approved these changes

2024-02-08 08:12 UTC, worryg0d commented on controllers/clusters/helpers.go
> +func autoHandleExternalChanges(c client.Client, r record.EventRecorder, obj Object) error {
fixed

2024-02-08 10:32 UTC, ribaraka approved these changes

2024-02-08 10:32 UTC, merged