total nodes number displaying for clusters was implemented
instaclustr/operator pull request #725
Opened 2024-02-26 14:25 UTC by tengu-alt

2024-02-26 15:55 UTC, ribaraka requested changes

2024-02-26 15:55 UTC, ribaraka commented on apis/clusters/v1beta1/cassandra_types.go
> +}
you use the same body func for all cluster CRDs. Please make this func generic

2024-02-26 16:42 UTC, ribaraka approved these changes

2024-02-27 10:57 UTC, worryg0d approved these changes

2024-02-27 14:29 UTC, testisnullus commented on pkg/instaclustr/mock/server/go/model_addon_bundles_options.go
> +	// The number of Redis Replica NodeCount to be created.
It's not critical, but let's revert these changes

2024-02-28 09:16 UTC, testisnullus requested changes

2024-02-28 09:16 UTC, testisnullus commented on apis/clusters/v1beta1/generic_status.go
> +//}
Let's remove it if unused

2024-02-28 09:21 UTC, tengu-alt commented on apis/clusters/v1beta1/generic_status.go
> +//}
agree, thank you

2024-02-28 09:24 UTC, testisnullus approved these changes

2024-02-28 09:26 UTC, merged